STACK_SIZE EQU $80 ; In words, not bytes

JOY_START  EQU 1<<7
JOY_SELECT EQU 1<<6
JOY_B      EQU 1<<5
JOY_A      EQU 1<<4
JOY_DOWN   EQU 1<<3
JOY_UP     EQU 1<<2
JOY_LEFT   EQU 1<<1
JOY_RIGHT  EQU 1<<0

STATE_PLAYING       EQU 0
STATE_GAME_OVER     EQU 1
STATE_NO_MORE_SPACE EQU 2
STATE_TITLE         EQU 3

VBLANKS_TO_WAIT_UNTIL_MOVE EQU 8
